sensor_topic:
  image_topic: /cam0/image_raw
  imu_topic: /imu0

feature_extractor:
    confidence_thresh: 0.01
    distance_thresh: 8
    horizontal_boarder_width: 10
    vertical_boarder_width: 10
    inference_width: 512
    inference_height: 512
    weight_path: /home/chenghe/catkin_ws/src/SuperVIO/data/superpoint.pt

feature_tracker:
  match_thresh: 2.0
  parallax_thresh: 10.0
  ratio_thresh: 1.0
  fundamental_filter: true

triangulator:
  view_angle_check: false
  baseline_check: false
  baseline_thresh: 0.1
  error_thresh: 2.0
  view_angle_thresh: 0.1

optimizer:
  linear_solver_type: "dense_schur"
  trust_region_strategy: "dogleg"
  max_iteration: 8
  num_threads: 4
  verbose: false
  max_solver_time: 1.0

estimation:
  min_num_match: 10
  sliding_window_size: 10
  parallax_thresh: 10.0
  linearized_ba_thresh: 0.1
  linearized_bg_thresh: 0.1
  max_preintegration_time: 10.0

imu:
  accelerator_noise: 0.1
  gyroscope_noise: 0.01
  accelerator_random_walk_noise: 0.001
  gyroscope_random_walk_noise: 0.0001

camera:
  camera_type: omni
  input_intrinsic:  [ 533.340727445877, 533.2556495307942, 254.64689387916482, 256.4835490935692, 1.7921879013]
  input_distortion: [-0.05972430882700243, 0.17468739202093328, 0.000737218969875311, 0.000574074894976456]
  output_intrinsic: [ 190.97847715128717, 190.9733070521226, 254.64689387916482, 256.4835490935692]
  input_image_height: 512
  input_image_width: 512
  output_image_height: 512
  output_image_width: 512
  use_gpu_for_undistortion: true

extrinsic:
  extrinsic_rotation: [ -0.99954072,  0.00741901, -0.02938199,
                         0.02910045, -0.03556579, -0.99894356,
                        -0.00845616, -0.9993398,   0.03533356]
  extrinsic_position: [0.04644611, -0.07105542,   -0.04342594]
  gravity_norm: 9.81
